### ISSUE TITLE
Type Error in webpack 2

### ISSUE THREAD

**Issue by nikoskalogridis** [rxaviers/skip-amd-webpack-plugin#4]
I have tried this with webpack 2 and the PR #36 on the globalize-webpack-plugin and it produces an Type error on line 23 of index.js.
```
var res = compiler.parser.evaluate("typeof (false)");
```
Changing this to:
```
var res = parser.evaluate("typeof (false)");
```
seems to fix the issue. I do not know if that is compatible with webpack 1 though. If it is I suppose we could change it.

**Comment by rxaviers** [comment]
Thanks. Released as `0.1.3`.

PS: This lib urgently needs tests...
